version: '3.8'

services:
  database:
    image: mysql:8.0  # Use MySQL 5.7 for better compatibility
    restart: always
    volumes:
      - data:/var/lib/mysql
      - ./data/import:/var/lib/mysql-files  # For importing CSV data
      - ./mysql-init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: TTRPG_DB
      MYSQL_USER: ttrpg_user
      MYSQL_PASSWORD: secretpass
      MYSQL_ALLOW_LOCAL_INFILE: 1  # Enable CSV imports
    ports:
      - "3306:3306"  # Map to 3307 on host to avoid conflicts
    networks:
      - stalker-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 4000:4000
    depends_on:
      database:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql+mysqlconnector://root:${MYSQL_PASSWORD:-secretpass}@database:3306/TTRPG_DB
      - SECRET_KEY=${JWT_SECRET_KEY:-YOUR_SECRET_KEY}
    networks:
      - stalker-net
    volumes:
      - ./backend:/app
      - ./data:/app/data
      - ./dist:/dist

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - app
    networks:
      - stalker-net

networks:
  stalker-net:
    driver: bridge

volumes:
  data: